# Generated by Django 5.1.2 on 2024-10-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_crop_quantity'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='zip',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='crops_grown',
            field=models.ManyToManyField(blank=True, related_name='farmers', to='crop.crop'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
