# Generated by Django 5.1.2 on 2024-10-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
