# Generated by Django 5.1.2 on 2024-10-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
