# Generated by Django 5.1.2 on 2024-10-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
