# Generated by Django 5.1.2 on 2024-10-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_sales_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='quantity_listed',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
