# Generated by Django 5.1.2 on 2024-10-13 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0006_crop_quantity_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='quantity_listed',
        ),
        migrations.CreateModel(
            name='QuantityAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_added', to='crop.crop')),
            ],
        ),
    ]
