# Generated by Django 5.1.2 on 2024-10-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0010_alter_crop_catogory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='catogory',
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('grain', 'Grain'), ('dairy', 'Dairy'), ('other', 'Other')], default=1),
            preserve_default=False,
        ),
    ]
