# Generated by Django 5.1.2 on 2024-10-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0011_remove_crop_catogory_crop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
