# Generated by Django 5.1.2 on 2024-11-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0012_crop_image_public_id_crop_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('grain', 'Grain'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('poultry', 'Poultry'), ('seafood', 'Seafood'), ('herb', 'Herb'), ('spice', 'Spice'), ('other', 'Other')]),
        ),
    ]
