# Generated by Django 5.1.2 on 2024-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0014_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('cereal', 'Cereal'), ('grain', 'Grain'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('poultry', 'Poultry'), ('seafood', 'Seafood'), ('herb', 'Herb'), ('spice', 'Spice'), ('other', 'Other')]),
        ),
    ]
