# Generated by Django 5.1.2 on 2024-12-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0018_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='image',
            new_name='image_url',
        ),
    ]
